##### Why numpy is required ??

Numpy - NUMerical PYthon library - A fundamental python library to perform complex numerical operations which is developed on top of Numeric library.

To perform complex math operations like statistics, differential/integral equations we don't have in built support in python. so we need numpy.

#### Advantage of numpy over python list ?

Numpy is developed on both python and C. Most of numpy is developed in C. So, performance wise numpy is fast.

ML model has to process millions of records, so in that case we have to go for numpy over python list where we require high speed.


Numpy has vectorization feature which improves performance while iteration


Numpy acts as backbone for ML libraries like Pandas, scikit-learn.
Ex: Pandas internally uses nd array to store data which is numpy data structure.

#### what is nd array in numpy ?

In numpy we can hold data using Array data structure.
Arrays which are created using numpy are called are nd arrays.


nd array --> N Dimensional array / Numpy array.

Numpy contains several functions which are reqiuired to create nd arrays and required operations.

#### Advantages of Numpy over python list ?

1. Performace is very high.
2. numpy array can hold homogenous data.

#### Applications of Numpy:

- To perform linear algebra functions.
- To perform linear regression, logistic regression.
- Neural networks
- K-means clustering
- Opeational research area etc


Numpy is fundamental required library for data science, ML, DL etc.

### Topics to be covered:
    
1. Creation of numpy array
2. Array operations
3. Array attributes
4. Array Indexing and Slicing
5. Broadcasting
6. Iterating over array
7. binary condition
8. copy and view operations
9. Sort and search operations
10. statistics functions
11. Linear algebra functions

### Numpy vs traditional python code (Performance Test)

In [16]:
# Dot product using numpy
%time

from datetime import datetime
import numpy as np

a = np.array([10,20,30])
b = np.array([1,2,3])
print(np.dot(a,b))


for i in range(10000000):
    np.dot(a,b)


# Dot product = (10*1)+(20*2)+(30*3) = 10+40+90 = 140

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 8.82 µs
140


In [17]:
# Python code
%time

def dot_product(a, b):
    res = 0
    for i,j in zip(a,b):
        res+=(i*j)
    return (res)

for i in range(10000000):
    dot_product(a,b)


CPU times: user 1e+03 ns, sys: 0 ns, total: 1e+03 ns
Wall time: 4.05 µs


How to create arrays in python ?

1. By using array module (not frequently used as library support is not much)
2. By using numpy module

In [24]:
import array

a=array.array('i', [10,20,30,40]) # here 'i' specify it's an int type array
print(type(a))
print('printing elements one by one: ')

for i in range(len(a)):
    print(a[i])

print('*********************')
for j in a:
    print(j)

<class 'array.array'>
printing elements one by one: 
10
20
30
40
*********************
10
20
30
40


In [25]:
# By using numpy library

import numpy as np
a=np.array([1,2,3,4])
print(type(a))

print('printing elements one by one: ')
for i in a:
    print(i)

<class 'numpy.ndarray'>
printing elements one by one: 
1
2
3
4


### Python list vs Numpy Array

##### Similarities:

1. Both can be used to hold/store data.
2. Order of insertion will be preserved. Hence indexing is possible.
3. Slicing is applicable for both.
4. Both are mutable. Once we create list/array we can modify the elements.


##### Differences:
1. List is in-built data type. But numpy is not in-built, we have to install and import numpy library explicitly.

2. List can hold heterogenous elements. Numpy array can hold homogenous elements.
    Ex: l = [1,"jayanthi", 3.45, True]
        a=numpy.array([10,20,30,40,50])

3. On arrays we can perform vector operations - the operations which can be operated on every element of the array. But on list vector operations cannot be performed.

    Ex: a=numpy.array([1,2,3,4])
        a+1 # [2,3,4,5]
        
        l = [1,2,3,4]
        l+1 # Gives Typeerror - Can only concatenate list not int
        l*2 # [1,2,3,4,1,2,3,4]
       
4. Numpy arrays consume less memory compared to list.

5. Numpy arrays are super fast.
6. Numpy arrays are more convenient to use while perform mathematical operations.

#### Creating numpy arrays:

Numpy has several functions to create nd array based on our requirement.

1. array()
2. arange()
3. zeros()
4. ones()
5. linspace()
6. eye()
7. identity()
8. emmpty()
9. random() - library functions ==> randint(), rand(), uniform(), randn(), normal(), shuffle()

#### Array Attributes

1. ndim - to get dimension of the array
2. shape - To get shape of the array
3. size - to get size of the array (number of elements present in an array)
4. dtype - to get datatype of array elements
5. itemsize - size of each element of the array in bytes.

In [38]:
a=np.array([1,2,3,4,5])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

1
(5,)
5
int64
8


##### Numpy data types:

In python we have data types - int, string, bool, complex, float etc.
Numpy has some extra data types. we can represent data types using a single char also.
i ==> integer ( by default int32)
b ==> boolean
u ==> unsigned integer (uint8, uint16, uint32, uint64)
f ==> float (float16, float32, float64) - default if float64
c ==> complex (complex64, complex128)
s ==> string
U ==> unicode string
M ==> datetime

In [41]:
# Create array with specified dtype

a=np.array([1,2,3,5], 'i8') # 8 bytes = 64 bits
print(a.dtype)

b=np.array([1,2,3,4,5], 'int8') # 8 bits
print(b.dtype)

c=np.array([1,2,3,4,5], 'i') # default int32
print(c.dtype)

int64
int8
int32


##### Convert type of existing array

Using astype() function.

In [44]:
a=np.array([1,2,3,4,5])
print(a.dtype)

b=a.astype('float64')
print(b.dtype)

int64
float64


##### Using corresponding data type

In [46]:
a=np.array([1,2,3,4,5])
print(a.dtype)

c=np.float64(a)
print(c.dtype)

int64
float64


In [88]:
a=np.array([1,2,3,4,5,0,6,-2])
print(a.dtype)

x=np.bool_(a)
print(x)
print(x.dtype)

int64
[ True  True  True  True  True False  True  True]
bool


#### Creation of nd array using arange function

In [90]:
a = np.arange(10)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
1
(10,)
10
int64


In [92]:
a = np.arange(1,11,3, dtype=float)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[ 1.  4.  7. 10.]
1
(4,)
4
float64


##### linspace function()

In [98]:
a=np.linspace(0,1) #between 0 and 1 we will get 50 linearly spaced values
print(a)
print(a.size)

print('********************')
a = np.linspace(0,10,3, dtype=int)
print(a)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
50
********************
[ 0  5 10]


##### arange() vs linspace()

#### Zeros() --> This function returns an array with all 0's. we can create any dimensional array

In [105]:
a = np.zeros(4)
print(a)

print('*******************')

a=np.zeros((4,3))
print(a)

print('*******************')

a=np.zeros((2,3,4))
print(a)

[0. 0. 0. 0.]
*******************
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
*******************
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


#### ones() --> generate an array with value "1".  Same as zeros()

In [106]:
a = np.ones(3)
print(a)

print('*******************')

a=np.ones((2,3))
print(a)

[1. 1. 1.]
*******************
[[1. 1. 1.]
 [1. 1. 1.]]


##### full() --> Generate any value

In [109]:
a = np.full(10, 2) # dimension and fill value
print(a)

print('\n*******************\n')

a = np.full((3,4),7)
print(a)

[2 2 2 2 2 2 2 2 2 2]

*******************

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


##### eye() --> To generate identity matrix

In [7]:
import numpy as np
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_functi

##### identity() 

##### empty()

In [12]:
a = np.empty(5)
print(a)

[ 1.    2.75  6.   10.75 17.  ]


#### Slicing on 2D array

In [56]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.shape)
print(a)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


syntax:

array_name[row, column]
array_name[begin:end:start, begin:end:start]


In [62]:
# fetch only first column elements
print(a[:,0:1])

print('************************')

#Fetch only second indexed row
print(a[1:2,:])

print('************************')

#Fetch only first two rows
print(a[:2,:])

print('************************')


#Fetch first and last row
print(a[::2,:])

[[1]
 [3]
 [5]]
************************
[[3 4]]
************************
[[1 2]
 [3 4]]
************************
[[1 2]
 [5 6]]
************************
[]


If we want to access multiple elements which are not in order (arbitrary elements) or based on some condition, then we can't use basic indexing and slicing operators. For this we should go for 
##### Advanced Indexing

Accessing multiple arbitrary elements:
syntax: array[x] --> x can be nd array or sequence like list or tuple which represents required indices.

###### Advanced Indexing on 1-D array

In [68]:
a=np.array([1,2,3,4,5,6,7,8,9])

# Fetch 1,3,8 from the above array.

# Way-1: create nd array with the required indices
# and then by passing that array as argument we can process corresponding elements

index_array = np.array([0,2,7])
print(a[index_array])



#Way-2: create list with required indices and by passing that list as arg we can get required elements

l = [0,2,7]
print(a[l])


# Access same element multiple times
print(a[[0,0,2,7,7]])

[1 3 8]
[1 3 8]
[1 1 3 8 8]


##### Advanced indexing on 2-D array


Syntax: array[row_indices, column_indices]

In [77]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
# print(a)

#Printing only diagonal indiced elements
l = [[0,1,2,3], [0,1,2,3]]
print(a[l])



#Fetch only 5 and 15 in a
l = [[1,3],[0,2]]
print(a[l])

[ 1  6 11 16]
[ 5 15]


/var/folders/1d/mdmrk41x47s4tlnxhhhbfp6m0000gq/T/ipykernel_47307/545759692.py:6: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  print(a[l])
/var/folders/1d/mdmrk41x47s4tlnxhhhbfp6m0000gq/T/ipykernel_47307/545759692.py:12: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  print(a[l])


#### Condition based selection

In [110]:
a=np.array([10, -5, 20, 40, -3, -1, 75])

#select all elements which are less than zero

boolean_array = a<0
print(boolean_array)

# By passing boolean array select array elements
print(a[boolean_array])


#short cut
print(a[a<0])


#select all elements which are greater than 10
print(a[a>10])

[False  True False False  True  True False]
[-5 -3 -1]
[-5 -3 -1]
[20 40 75]


#### condition based selection on 2D array

In [85]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a[a>10])

[11 12 13 14 15 16]


### Arithmetic Operations on numpy array

+, -, *, /, %, **, //

All arithmetic operators are applicable on any dimensional numpy arrays with a scalar value.

In numpy we won't get ZeroDivisionError. If the result is undefined (0/0) then we will get NaN (not a number). If the result is infinity then it is treated as "inf".

#### Arithmetic operators for numpy arrays with array

In [86]:
a = np.arange(6)
print(a/0)

[nan inf inf inf inf inf]


/var/folders/1d/mdmrk41x47s4tlnxhhhbfp6m0000gq/T/ipykernel_47307/2967758913.py:2: RuntimeWarning: divide by zero encountered in true_divide
  print(a/0)
/var/folders/1d/mdmrk41x47s4tlnxhhhbfp6m0000gq/T/ipykernel_47307/2967758913.py:2: RuntimeWarning: invalid value encountered in true_divide
  print(a/0)


In [87]:
print(a/np.inf)

[0. 0. 0. 0. 0. 0.]


In [14]:
import jovian

jovian.commit()

<IPython.core.display.Javascript object>

ApiError: File upload failed: (HTTP 404) Gist not found